// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qodmlcdqpderrvrcwzlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZG1sY2RxcGRlcnJ2cmN3emxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTA2NjAsImV4cCI6MjA1Nzk4NjY2MH0.ZZ44-vxdN3UBnIaTIVdR_Dc9CCVx-wZ1DAttHIjlVuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);